version: "3.8"

services:
  base:
    image: bitnetdeps:latest
    build:
      context: .
      dockerfile: Dockerfile.base
    env_file:
      - ./Pipeline/.env
  bitnet:
    depends_on:
    - base
    build: 
      context: .
      dockerfile: Dockerfile.main
    ports:
      - "8501:8501"
    env_file:
      - ./Pipeline/.env   
    entrypoint: "python main.py $ARGS"
    volumes: 
    - ./Pipeline:/app/Pipeline
    - ./Patch:/app/Patch